/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.uttt.ejecutor;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mx.edu.uttt.busines.peliculaBO;
import mx.edu.uttt.transfer.peliculasVO;

/**
 *
 * @author crist
 */
public class peliculasVista extends javax.swing.JFrame {

    DefaultTableModel tabPeliculas=new DefaultTableModel();
    int id;

    /**
     * Creates new form peliculasVista
     */
    public peliculasVista() {
        initComponents();
        llenarTabla();
        btnEliminar.setVisible(false);
        btnEditar.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setTitle("TransferObject");

//        tabPeliculas = new DefaultTableModel();
//        tabPeliculas.addColumn("id");
//        tabPeliculas.addColumn("Titulo");
//        tabPeliculas.addColumn("Genero");
//        tabPeliculas.addColumn("Descripcion");
//        tabPeliculas.addColumn("Precio");
//        tabPeliculas.addColumn("Stock");
//        this.TbPeliculas.setModel(tabPeliculas);
    }
    public void limpiarTabla(){
    int fila=TbPeliculas.getRowCount();
        for (int i = 0; i < fila; i++) {
            tabPeliculas.removeRow(0);
        }
    }
    public void limpiarCampos(){
txtId.setText(null);
        txtTitulo.setText(null);
        txtGenero.setText(null);
        txaDescripcion.setText(null);
        txtPrecio.setText(null);
        txtStock.setText(null);
}
    public void llenarTabla() {

   tabPeliculas.setColumnIdentifiers(new String[]{"ID producto","Nombre","Precio","Stock","Categoria","Proveedor"});
   TbPeliculas.setModel(tabPeliculas);
        peliculaBO peliBO = new peliculaBO();
        ArrayList<peliculasVO>List = (ArrayList<peliculasVO>)(peliBO.getAllPeliculasVO());
        
        for (int i = 0; i < List.size(); i++){
            tabPeliculas.addRow(new Object[]{List.get(i).getId(),List.get(i).getTitulo()
                    ,List.get(i).getGenero(),List.get(i).getDescripcion()
                    ,List.get(i).getPrecio(),List.get(i).getStock()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        btnIngresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtGenero = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lbStock = new javax.swing.JLabel();
        txtPelicula = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPeliculas = new javax.swing.JTable();
        lbTitulo = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        lbStock.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbStock.setForeground(new java.awt.Color(0, 0, 102));
        lbStock.setText("Stock");

        txtPelicula.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        txtPelicula.setForeground(new java.awt.Color(153, 0, 0));
        txtPelicula.setText("Peliculas");

        lbId.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbId.setForeground(new java.awt.Color(0, 0, 102));
        lbId.setText("Id");

        TbPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TbPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbPeliculas);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 102));
        lbTitulo.setText("Titulo");

        lbGenero.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbGenero.setForeground(new java.awt.Color(0, 0, 102));
        lbGenero.setText("Genero");

        lbPrecio.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(0, 0, 102));
        lbPrecio.setText("Precio");

        lbDescripcion.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbDescripcion.setForeground(new java.awt.Color(0, 0, 102));
        lbDescripcion.setText("Descripción");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txaDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(txtPelicula))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbGenero))
                    .addComponent(lbDescripcion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbPrecio)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lbStock)
                        .addGap(15, 15, 15)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnIngresar)
                .addGap(107, 107, 107)
                .addComponent(btnEditar)
                .addGap(109, 109, 109)
                .addComponent(btnEliminar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPelicula))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbId)
                        .addGap(13, 13, 13)
                        .addComponent(lbTitulo)
                        .addGap(23, 23, 23)
                        .addComponent(lbGenero)
                        .addGap(23, 23, 23)
                        .addComponent(lbDescripcion)
                        .addGap(103, 103, 103)
                        .addComponent(lbPrecio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStock)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        peliculaBO peli = new peliculaBO();
        peliculasVO pelivo = new peliculasVO();
        pelivo.setId(Integer.parseInt(txtId.getText()));
        pelivo.setTitulo(txtTitulo.getText());
        pelivo.setGenero(txtGenero.getText());
        pelivo.setDescripcion(txaDescripcion.getText());
        pelivo.setPrecio(Double.parseDouble(txtPrecio.getText()));
        pelivo.setStock(Integer.parseInt(txtStock.getText()));
 
        peli.addPelicula(pelivo);
        limpiarTabla();
        llenarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtId.enable(true);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        peliculaBO peli = new peliculaBO();
        peliculasVO pelivo = new peliculasVO();
        pelivo.setId(Integer.parseInt(txtId.getText()));
        pelivo.setTitulo(txtTitulo.getText());
        pelivo.setGenero(txtGenero.getText());
        pelivo.setDescripcion(txaDescripcion.getText());
        pelivo.setPrecio(Double.parseDouble(txtPrecio.getText()));
        pelivo.setStock(Integer.parseInt(txtStock.getText()));
 
        peli.updatePelicula(pelivo);
        limpiarTabla();
        llenarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        txtId.enable(true);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        peliculaBO pelibo = new peliculaBO();
        peliculasVO pelivo = new peliculasVO();
        pelivo.setId(Integer.parseInt(txtId.getText()));
        pelivo.setTitulo(txtTitulo.getText());
        pelivo.setGenero(txtGenero.getText());
        pelivo.setDescripcion(txaDescripcion.getText());
        pelivo.setPrecio(Double.parseDouble(txtPrecio.getText()));
        pelivo.setStock(Integer.parseInt(txtStock.getText()));
        pelibo.deletePeliculas(pelivo);
        limpiarTabla();
        llenarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TbPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPeliculasMouseClicked
txtId.enable(false);
btnEditar.setVisible(true);
        btnEliminar.setVisible(true);
        int fila= TbPeliculas.getSelectedRow();
        txtId.setText(TbPeliculas.getValueAt(fila, 0).toString());
        txtTitulo.setText(TbPeliculas.getValueAt(fila, 1).toString());
        txtGenero.setText(TbPeliculas.getValueAt(fila, 2).toString());
        txaDescripcion.setText(TbPeliculas.getValueAt(fila, 3).toString());
        txtPrecio.setText(TbPeliculas.getValueAt(fila, 4).toString());
        txtStock.setText(TbPeliculas.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_TbPeliculasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peliculasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peliculasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peliculasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peliculasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peliculasVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbPeliculas;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbStock;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtPelicula;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
